### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "shinha@test.com",
    "password": "1234"
}

### Sign in as an existing user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "shinha@test.com",
    "password":"1234"
}

### Get currently signed in user
GET http://localhost:3000/auth/whoami

### Find a particular user with Id
GET http://localhost:3000/auth/1

### Find all users with given email
GET http://localhost:3000/auth?email=ab@a.com

### Delete an user with given Id
DELETE http://localhost:3000/auth/89

### Update a user
PATCH http://localhost:3000/auth/3
content-type: application/json  

{
    "password": "ab@a.com"
}